package cn.cbsd.dogtag.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.cbsd.dogtag.Data.DogMessageBean;
import cn.cbsd.dogtag.Data.DogViolationBean;

import cn.cbsd.dogtag.greendao.DogMessageBeanDao;
import cn.cbsd.dogtag.greendao.DogViolationBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dogMessageBeanDaoConfig;
    private final DaoConfig dogViolationBeanDaoConfig;

    private final DogMessageBeanDao dogMessageBeanDao;
    private final DogViolationBeanDao dogViolationBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dogMessageBeanDaoConfig = daoConfigMap.get(DogMessageBeanDao.class).clone();
        dogMessageBeanDaoConfig.initIdentityScope(type);

        dogViolationBeanDaoConfig = daoConfigMap.get(DogViolationBeanDao.class).clone();
        dogViolationBeanDaoConfig.initIdentityScope(type);

        dogMessageBeanDao = new DogMessageBeanDao(dogMessageBeanDaoConfig, this);
        dogViolationBeanDao = new DogViolationBeanDao(dogViolationBeanDaoConfig, this);

        registerDao(DogMessageBean.class, dogMessageBeanDao);
        registerDao(DogViolationBean.class, dogViolationBeanDao);
    }
    
    public void clear() {
        dogMessageBeanDaoConfig.clearIdentityScope();
        dogViolationBeanDaoConfig.clearIdentityScope();
    }

    public DogMessageBeanDao getDogMessageBeanDao() {
        return dogMessageBeanDao;
    }

    public DogViolationBeanDao getDogViolationBeanDao() {
        return dogViolationBeanDao;
    }

}
