package cn.cbsd.dogtag.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.cbsd.dogtag.Data.MyBitmapListConvert;
import java.util.List;

import cn.cbsd.dogtag.Data.DogMessageBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOG_MESSAGE_BEAN".
*/
public class DogMessageBeanDao extends AbstractDao<DogMessageBean, Long> {

    public static final String TABLENAME = "DOG_MESSAGE_BEAN";

    /**
     * Properties of entity DogMessageBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PersonName = new Property(1, String.class, "personName", false, "PERSON_NAME");
        public final static Property PersonId = new Property(2, String.class, "personId", false, "PERSON_ID");
        public final static Property Address = new Property(3, String.class, "address", false, "ADDRESS");
        public final static Property DogName = new Property(4, String.class, "dogName", false, "DOG_NAME");
        public final static Property DogType = new Property(5, String.class, "dogType", false, "DOG_TYPE");
        public final static Property DogTagNum = new Property(6, String.class, "dogTagNum", false, "DOG_TAG_NUM");
        public final static Property DogTagQRCode = new Property(7, String.class, "dogTagQRCode", false, "DOG_TAG_QRCODE");
        public final static Property StartDate = new Property(8, String.class, "startDate", false, "START_DATE");
        public final static Property StopDate = new Property(9, String.class, "stopDate", false, "STOP_DATE");
        public final static Property Bitmaps = new Property(10, String.class, "bitmaps", false, "BITMAPS");
    }

    private final MyBitmapListConvert bitmapsConverter = new MyBitmapListConvert();

    public DogMessageBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DogMessageBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOG_MESSAGE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PERSON_NAME\" TEXT," + // 1: personName
                "\"PERSON_ID\" TEXT," + // 2: personId
                "\"ADDRESS\" TEXT," + // 3: address
                "\"DOG_NAME\" TEXT," + // 4: dogName
                "\"DOG_TYPE\" TEXT," + // 5: dogType
                "\"DOG_TAG_NUM\" TEXT," + // 6: dogTagNum
                "\"DOG_TAG_QRCODE\" TEXT," + // 7: dogTagQRCode
                "\"START_DATE\" TEXT," + // 8: startDate
                "\"STOP_DATE\" TEXT," + // 9: stopDate
                "\"BITMAPS\" TEXT);"); // 10: bitmaps
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOG_MESSAGE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DogMessageBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String personName = entity.getPersonName();
        if (personName != null) {
            stmt.bindString(2, personName);
        }
 
        String personId = entity.getPersonId();
        if (personId != null) {
            stmt.bindString(3, personId);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(4, address);
        }
 
        String dogName = entity.getDogName();
        if (dogName != null) {
            stmt.bindString(5, dogName);
        }
 
        String dogType = entity.getDogType();
        if (dogType != null) {
            stmt.bindString(6, dogType);
        }
 
        String dogTagNum = entity.getDogTagNum();
        if (dogTagNum != null) {
            stmt.bindString(7, dogTagNum);
        }
 
        String dogTagQRCode = entity.getDogTagQRCode();
        if (dogTagQRCode != null) {
            stmt.bindString(8, dogTagQRCode);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(9, startDate);
        }
 
        String stopDate = entity.getStopDate();
        if (stopDate != null) {
            stmt.bindString(10, stopDate);
        }
 
        List bitmaps = entity.getBitmaps();
        if (bitmaps != null) {
            stmt.bindString(11, bitmapsConverter.convertToDatabaseValue(bitmaps));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DogMessageBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String personName = entity.getPersonName();
        if (personName != null) {
            stmt.bindString(2, personName);
        }
 
        String personId = entity.getPersonId();
        if (personId != null) {
            stmt.bindString(3, personId);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(4, address);
        }
 
        String dogName = entity.getDogName();
        if (dogName != null) {
            stmt.bindString(5, dogName);
        }
 
        String dogType = entity.getDogType();
        if (dogType != null) {
            stmt.bindString(6, dogType);
        }
 
        String dogTagNum = entity.getDogTagNum();
        if (dogTagNum != null) {
            stmt.bindString(7, dogTagNum);
        }
 
        String dogTagQRCode = entity.getDogTagQRCode();
        if (dogTagQRCode != null) {
            stmt.bindString(8, dogTagQRCode);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(9, startDate);
        }
 
        String stopDate = entity.getStopDate();
        if (stopDate != null) {
            stmt.bindString(10, stopDate);
        }
 
        List bitmaps = entity.getBitmaps();
        if (bitmaps != null) {
            stmt.bindString(11, bitmapsConverter.convertToDatabaseValue(bitmaps));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DogMessageBean readEntity(Cursor cursor, int offset) {
        DogMessageBean entity = new DogMessageBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // personName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // personId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // address
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // dogName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // dogType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // dogTagNum
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // dogTagQRCode
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // startDate
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // stopDate
            cursor.isNull(offset + 10) ? null : bitmapsConverter.convertToEntityProperty(cursor.getString(offset + 10)) // bitmaps
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DogMessageBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPersonName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPersonId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAddress(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDogName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDogType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDogTagNum(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDogTagQRCode(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStartDate(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setStopDate(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBitmaps(cursor.isNull(offset + 10) ? null : bitmapsConverter.convertToEntityProperty(cursor.getString(offset + 10)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DogMessageBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DogMessageBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DogMessageBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
